// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLkMiJMGu0fIhKEJbKmiMk45aODBTY7M',
    appId: '1:792338779472:web:ac7b527df03e6e02c0b055',
    messagingSenderId: '792338779472',
    projectId: 'bilbil-35e16',
    authDomain: 'bilbil-35e16.firebaseapp.com',
    storageBucket: 'bilbil-35e16.firebasestorage.app',
    measurementId: 'G-SRZ9MT23XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDseLKa7ICjsDswAPvvjvYEcpmJosVANW0',
    appId: '1:792338779472:android:eb16aa9767880093c0b055',
    messagingSenderId: '792338779472',
    projectId: 'bilbil-35e16',
    storageBucket: 'bilbil-35e16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIjPmrXnV4uB-2XVQWmt8aKdHzidhB1I',
    appId: '1:792338779472:ios:cca7defdd3a368e6c0b055',
    messagingSenderId: '792338779472',
    projectId: 'bilbil-35e16',
    storageBucket: 'bilbil-35e16.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOIjPmrXnV4uB-2XVQWmt8aKdHzidhB1I',
    appId: '1:792338779472:ios:cca7defdd3a368e6c0b055',
    messagingSenderId: '792338779472',
    projectId: 'bilbil-35e16',
    storageBucket: 'bilbil-35e16.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALLkMiJMGu0fIhKEJbKmiMk45aODBTY7M',
    appId: '1:792338779472:web:50cdb5fb04e73e0ac0b055',
    messagingSenderId: '792338779472',
    projectId: 'bilbil-35e16',
    authDomain: 'bilbil-35e16.firebaseapp.com',
    storageBucket: 'bilbil-35e16.firebasestorage.app',
    measurementId: 'G-1F2QHN8N0P',
  );
}
